package au.edu.unsw.soacourse.pinkslip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-06-05T17:14:31.139+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/pinkslip", name = "PSCheckPT")
@XmlSeeAlso({au.edu.unsw.soacourse.pinkslipdefinitions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PSCheckPT {

    @WebResult(name = "approvalMessage", targetNamespace = "http://soacourse.unsw.edu.au/pinkslipdefinitions", partName = "renewalresp")
    @WebMethod(operationName = "PSCheck", action = "http://soacourse.unsw.edu.au/pinkslip/PSCheck")
    public au.edu.unsw.soacourse.pinkslipdefinitions.ApprovalType psCheck(
        @WebParam(partName = "renewalreq", name = "renewalInformationMessage", targetNamespace = "http://soacourse.unsw.edu.au/pinkslipdefinitions")
        au.edu.unsw.soacourse.pinkslipdefinitions.RenewalInputType renewalreq
    );

    @WebResult(name = "ageMessage", targetNamespace = "http://soacourse.unsw.edu.au/pinkslipdefinitions", partName = "renewalresp")
    @WebMethod(operationName = "VehicleAge", action = "http://soacourse.unsw.edu.au/pinkslip/VehicleAge")
    public au.edu.unsw.soacourse.pinkslipdefinitions.AgeType vehicleAge(
        @WebParam(partName = "renewalreq", name = "vehicleAgeMessage", targetNamespace = "http://soacourse.unsw.edu.au/pinkslipdefinitions")
        au.edu.unsw.soacourse.pinkslipdefinitions.RenewalInputType renewalreq
    );
}
