package au.edu.unsw.soacourse.rms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import au.edu.unsw.soacourse.greenslip.GSCheckPT;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-19T21:16:12.239+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "RMSService", 
                  wsdlLocation = "http://localhost:6060/ode/deployment/bundles/BPEL_RMS/RMSArtifacts.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/rms") 
public class RMSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/rms", "RMSService");
    public final static QName RMSPort = new QName("http://soacourse.unsw.edu.au/rms", "RMSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:6060/ode/deployment/bundles/BPEL_RMS/RMSArtifacts.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RMSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:6060/ode/deployment/bundles/BPEL_RMS/RMSArtifacts.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RMSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RMSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RMSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RMSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RMSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GSCheckPT
     */
    @WebEndpoint(name = "RMSPort")
    public GSCheckPT getRMSPort() {
        return super.getPort(RMSPort, GSCheckPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GSCheckPT
     */
    @WebEndpoint(name = "RMSPort")
    public GSCheckPT getRMSPort(WebServiceFeature... features) {
        return super.getPort(RMSPort, GSCheckPT.class, features);
    }

}
