package au.edu.unsw.soacourse.greenslip;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-06-05T17:14:43.640+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "GreenSlipCheck", 
                  wsdlLocation = "file:/Users/Henry/eclipse%20EE/workspace/GreenSlipCheck/src/main/resources/wsdl/greenslip.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/greenslip") 
public class GreenSlipCheck extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/greenslip", "GreenSlipCheck");
    public final static QName GreenSlipSOAP = new QName("http://soacourse.unsw.edu.au/greenslip", "GreenSlipSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Henry/eclipse%20EE/workspace/GreenSlipCheck/src/main/resources/wsdl/greenslip.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreenSlipCheck.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Henry/eclipse%20EE/workspace/GreenSlipCheck/src/main/resources/wsdl/greenslip.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreenSlipCheck(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreenSlipCheck(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreenSlipCheck() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipCheck(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipCheck(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreenSlipCheck(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GSCheckPT
     */
    @WebEndpoint(name = "GreenSlipSOAP")
    public GSCheckPT getGreenSlipSOAP() {
        return super.getPort(GreenSlipSOAP, GSCheckPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GSCheckPT
     */
    @WebEndpoint(name = "GreenSlipSOAP")
    public GSCheckPT getGreenSlipSOAP(WebServiceFeature... features) {
        return super.getPort(GreenSlipSOAP, GSCheckPT.class, features);
    }

}
