package au.edu.unsw.soacourse.greenslip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-06-05T17:14:43.596+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/greenslip", name = "GSCheckPT")
@XmlSeeAlso({au.edu.unsw.soacourse.greenslipdefinitions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GSCheckPT {

    @WebResult(name = "approvalMessage", targetNamespace = "http://soacourse.unsw.edu.au/greenslipdefinitions", partName = "renewalresp")
    @WebMethod(operationName = "GSCheck", action = "http://soacourse.unsw.edu.au/greenslip/GSCheck")
    public au.edu.unsw.soacourse.greenslipdefinitions.ApprovalType gsCheck(
        @WebParam(partName = "renewalreq", name = "renewalInformationMessage", targetNamespace = "http://soacourse.unsw.edu.au/greenslipdefinitions")
        au.edu.unsw.soacourse.greenslipdefinitions.RenewalInputType renewalreq
    );
}
